import Head from 'next/head'
import { Inter } from 'next/font/google'
import conectarDB from '@/lib/dbConnect'
import Movie from '@/models/Movie'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({movies}) {
  console.log(movies)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>Movies</h1>
        <Link href={'/new'} className='btn btn-primary w-100 mb-2'>
            Agregar
        </Link>
        {
          movies.map(({_id, title, plot }) => (
            <div className="card mb-2" key={_id}>
              <div className="h5 text-uppercase">{title}</div>
              <p className="fw-light">{plot}</p>
              <Link className="btn btn-success btn-sm" href={`/${_id}`}>
            Mas Info...
          </Link>
            </div>
          ))
        }
      </main>
    </>
  )
}

export async function getServerSideProps() {
  try {
    await conectarDB()

    const res = await Movie.find({})
    /* console.log(res) */
    const movies = res.map(doc => {
      const movie = doc.toObject()
      movie._id = `${movie._id}`
      return movie
    })

    return {
      props: { movies }
    }
  } catch (error) {
    console.log(error)
    return {
      props: { success: false, error: 'Error!' }
    }
  }
}
